/*
* Copyright(C) 2011-2012 Alibaba Group Holding Limited
* 
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License version 2 as
* published by the Free Software Foundation.
*/


/*
 * default_mysql_sysvar_for_tdh_socket.hpp
 *
 *  Created on: 2012-2-15
 *      Author: wentong
 */

#ifndef DEFAULT_MYSQL_SYSVAR_FOR_TDH_SOCKET_HPP_
#define DEFAULT_MYSQL_SYSVAR_FOR_TDH_SOCKET_HPP_

#define DEFAULT_TDHS_LISTEN_PORT 9999

#define DEFAULT_TDHS_LOG_LEVEL 3

#define DEFAULT_TDHS_IO_THREAD_NUM 4

#define DEFAULT_TDHS_THREAD_NUM 8

#define DEFAULT_TDHS_SLOW_READ_THREAD_NUM 28

#define DEFAULT_TDHS_WRITE_THREAD_NUM 1

#define DEFAULT_TDHS_CACHE_TABLE_ON TRUE

#define DEFAULT_TDHS_CACHE_TABLE_NUM_FOR_THD 3

#define DEFAULT_TDHS_OPTIMIZE_ON FALSE

#define DEFAULT_TDHS_OPTIMIZE_BLOOM_FILTER_GROUP 5

#define DEFAULT_TDHS_OPTIMIZE_BLOOM_FILTER_NUM_BUCKETS (16 * 1024)

#define DEFAULT_TDHS_OPTIMIZE_GUESS_HOT_REQUEST_NUM (500 * 10000)

#define DEFAULT_TDHS_MONITOR_INTERVAL 5

#define DEFAULT_TDHS_THREAD_STRATEGY_REQUESTS_LV_1 128

#define DEFAULT_TDHS_THREAD_STRATEGY_REQUESTS_LV_2 1024

#define DEFAULT_TDHS_CONCURRENCY_INSERT FALSE

#define DEFAULT_TDHS_CONCURRENCY_UPDATE FALSE

#define DEFAULT_TDHS_CONCURRENCY_DELETE FALSE

#define DEFAULT_TDHS_AUTH_ON FALSE

#define DEFAULT_TDHS_AUTH_READ_CODE NULL

#define DEFAULT_TDHS_AUTH_WRITE_CODE NULL

#define DEFAULT_TDHS_THROTTLE_ON FALSE

#define DEFAULT_TDHS_SLOW_READ_LIMITS 2

#define DEFAULT_TDHS_WRITE_BUFF_SIZE (8*1024)

#define DEFAULT_TDHS_GROUP_COMMIT TRUE

#define DEFAULT_TDHS_GROUP_COMMIT_LIMITS 0

#define DEFAULT_TDHS_QUICK_REQUEST_THREAD_TASK_COUNT_LIMIT 0

#define DEFAULT_TDHS_SLOW_REQUEST_THREAD_TASK_COUNT_LIMIT 0

#define DEFAULT_TDHS_WRITE_REQUEST_THREAD_TASK_COUNT_LIMIT 0

#endif /* DEFAULT_MYSQL_SYSVAR_FOR_TDH_SOCKET_HPP_ */
